version: '3'

services:
    client:
      build:
          context: ./public
          dockerfile: Dockerfile
#      networks:
#        - internal_network
      ports:
        - "8080:8080"
      volumes:
        - .:/usr/src/app


    go-webrtfc:
      build:
        context: ./play-from-disk-h264
        dockerfile: Dockerfile
#      networks:
#        - internal_network
      ports:
        - "4000:4000"

networks:
  external_network:
    driver: bridge
  internal_network:
    driver: bridge
